### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#170]
Sometimes the tests fail, but work again after restarting:
- https://github.com/leanprover/vscode-lean4/actions/runs/2186659870/attempts/1
- https://github.com/leanprover/vscode-lean4/actions/runs/2194375381/attempts/1

**Comment by Vtec234** [comment]
The second of these is an instance of #165 . The first one I have not seen before.

**Comment by lovettchris** [comment]
I believe this is fixed now.

**Comment by Vtec234** [comment]
We are still seeing them, unfortunately. For example [here](https://github.com/leanprover/vscode-lean4/runs/6528944512?check_suite_focus=true).

**Comment by lovettchris** [comment]
> We are still seeing them, unfortunately. For example [here](https://github.com/leanprover/vscode-lean4/runs/6528944512?check_suite_focus=true).

are you sure your branch is in sync with master?

**Comment by Vtec234** [comment]
It was not! Thank you for pointing it out.

**Comment by gebner** [comment]
And they seem to be back: https://github.com/leanprover/vscode-lean4/runs/6691857368?check_suite_focus=true

**Comment by lovettchris** [comment]
I think this might be a new bug the output contains this, I haven't seen this one before.  Do you recognize this "incorrect position" language from the LSP side?

```
version.lean:3:4
Error updating: Error fetching goals: {"stack":"Error: Incorrect position 'file:///d%3A/a/vscode-lean4/vscode-lean4/vscode-lean4/test/test-fixtures/simple/test/version.lean:2:4' in RPC call\n\tat d:\\a\\vscode-lean4\\vscode-lean4\\vscode-lean4\\dist\\extension.js:2:542515\n\tat d:\\a\\vscode-lean4\\vscode-lean4\\vscode-lean4\\dist\\extension.js:2:542809\n\tat Immediate.<anonymous> (d:\\a\\vscode-lean4\\vscode-lean4\\vscode-lean4\\dist\\extension.js:2:543171)\n\tat processImmediate (node:internal/timers:464:21)","message":"Incorrect position 'file:///d%3A/a/vscode-lean4/vscode-lean4/vscode-lean4/test/test-fixtures/simple/test/version.lean:2:4' in RPC call","code":-32602}. Try again.
All Messages (1)
version.lean:1:0
invalid output from `c:\Users\runneradmin\.elan\toolchains\leanprover--lean4---nightly\bin\lake.exe print-paths Init Lake`:

stderr:
```

**Comment by lovettchris** [comment]
I think the tests are robust enough now

**Comment by gebner** [comment]
The last three builds on master failed since we merged #204 (and the tests were green on the PR).  Do you have any idea what's going on?

**Comment by lovettchris** [comment]
Interesting, seems there is more latency on infoview in the test machines, this should help: https://github.com/leanprover/vscode-lean4/pull/205

**Comment by lovettchris** [comment]
PR #205 also didn't pass - it is getting weird errors I am not seeing locally.  There was a [rerression in lean](https://github.com/leanprover/lean4/issues/1260) last night that might be part of this...

**Comment by lovettchris** [comment]
This might also be part of the problem, there is a tiny change in behavior in Lean:

```lean
#eval [1, 1+1, 1+1+1]
```
used to print this in the infoview:

![image](https://user-images.githubusercontent.com/18707114/176316407-c8a17d8e-c7ae-4313-9d28-0f815817813c.png)

Now it prints this:

![image](https://user-images.githubusercontent.com/18707114/176316425-abd08f98-d412-4087-9849-5992b28813fa.png)

So I end up pinning the wrong thing, the test expected to pin [1,2,3] not "List Nat".

**Comment by lovettchris** [comment]
I filed this new bug:
https://github.com/leanprover/lean4/issues/1263

**Comment by lovettchris** [comment]
that bug was closed "by design" so we'll go with the fix to the test that adds a space at the end of the line.
